apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
  # Service name
  name: node-app-service
spec:
  selector:
    # Selector for Pods
    app: node-app
  ports:
    # Port Map
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer